# Ansible playbook to create a Rackspace Linux-Tomcat-MySQL-Java Cloud Server
# Run with: ansible-playbook -i hosts.yml rax-ltmj.yml -vvv
# For image and flavor list check file lists.txt


---
- name: Build environment
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Server create request
      local_action:
        module: rax
        name: test
        flavor: 2
        image: 41e59c5f-530b-423c-86ec-13b23de49288
        disk_config: manual
        networks:
          - public
          - private
        region: LON
        state: present
        wait: yes
      register: rax

    - name: Add servers to web host group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }}"
        ansible_ssh_user: root
        groupname: web
      with_items: rax.instances
      when: rax.action == 'create'
    
    - name: Wait few seconds before connection
      wait_for: port=22 delay=20

- name: Install Java, MySQL, Tomcat
  hosts: web

  roles:
#    - common
    - java
    - tomcat
#    - { role: mysql, when: db_choice == 'mysql' }
#    - { role: percona, when: db_choice == 'percona' }
#    - httpd
#    - php
#    - { role: varnish, when: varnish_install == 'install' }
#    - { role: magento, when: magento_install == 'install' }
